//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_21351029
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Request
    {
        
        [Display(Name = "Codigo de solicitud")]
        public string request_code { get; set; }
        
        [Display(Name = "Numero de cuenta")]
        public string account_number { get; set; }

        [Required]
        [Display(Name = "Fecha solicitada")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime request_date { get; set; }
        
        [Display(Name = "Fecha de solicitud")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime date_requested { get; set; }
        
        [Display(Name = "Estado de solicitud")]
        public string status { get; set; }
        
        [Display(Name = "Codigo de clase")]
        public string class_code { get; set; }
        
        [Display(Name = "Hora solicitada")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> request_time { get; set; }
        
        [Display(Name = "Hora")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:HH:mm}")]
        public Nullable<System.DateTime> hour { get; set; }
    }
}
