//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_21351029
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcription
    {
        public string subcription_code { get; set; }
        public string account_number { get; set; }
        public string tutorial_code { get; set; }
    }
}
