//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_21351029
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tutorial
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "Tutor")]
        public string tutor_code { get; set; }

        [Required]
        [Display(Name = "Clase")]
        public string class_code { get; set; }

        [Required]
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime tutorial_date { get; set; }

        [Required]
        [Display(Name = "Cantidad De Alumnos")]
        public int student_amount { get; set; }

        [Required]
        [Display(Name = "Hora")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:HH:mm}")]
        public System.DateTime hour { get; set; }

        [Required]
        [Display(Name = "Fecha De Inicio")]
        public System.DateTime start_date { get; set; }

        [Required]
        [Display(Name = "Fecha De Finalizacion")]
        public System.DateTime end_date { get; set; }

        public string text { get; set; }

        [Display(Name = "Tutor")]
        public string tutor_name { get; set; }

        [Display(Name = "Clase")]
        public string class_name { get; set; }
    }
}
