//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_21351029
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutorial
    {
        public string tutorial_code { get; set; }
        public string tutor_code { get; set; }
        public string class_code { get; set; }
        public System.DateTime tutorial_date { get; set; }
        public System.TimeSpan tutorial_time { get; set; }
        public Nullable<int> student_amount { get; set; }
    }
}
